# pull official base image
FROM node:14.14.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH

# install app dependencies
COPY ./package.json ./

RUN  npm install --force 


# add app
COPY . .

# start app
CMD ["npm", "run", "dev"]